
version: '3'
services:
    head:
        image: "ompc-mpi-base:latest"
        hostname: head
        stdin_open: true    # docker run -i
        tty: true           # docker run -t
        volumes:
            - .:/volume/
        cap_add:
            - NET_ADMIN
            
    dc-01-standard-1:
        image: "ompc-mpi-base:latest"
        hostname: dc-01-standard-1
        stdin_open: true 
        tty: true
        volumes:
            - .:/volume/
        deploy:
            replicas: 4
            resources:
                limits:
                  cpus: '4.0'
                  memory: 16G
        cap_add:
            - NET_ADMIN
 
    dc-02-standard-1:
        image: "ompc-mpi-base:latest"
        hostname: dc-02-standard-1
        stdin_open: true 
        tty: true
        volumes:
            - .:/volume/
        deploy:
            replicas: 8
            resources:
                limits:
                  cpus: '8.0'
                  memory: 32G
        cap_add:
            - NET_ADMIN
            
    dc-03-standard-2:
        image: "ompc-mpi-base:latest"
        hostname: dc-03-standard-2
        stdin_open: true 
        tty: true
        volumes:
            - .:/volume/
        deploy:
            replicas: 4
            resources:
                limits:
                  cpus: '8.0'
                  memory: 32G
        cap_add:
            - NET_ADMIN
            
    dc-04-standard-2:
        image: "ompc-mpi-base:latest"
        hostname: dc-04-standard-2
        stdin_open: true 
        tty: true
        volumes:
            - .:/volume/
        deploy:
            replicas: 8
            resources:
                limits:
                  cpus: '16.0'
                  memory: 64G
        cap_add:
            - NET_ADMIN
    
    dc-05-standard-4:
        image: "ompc-mpi-base:latest"
        hostname: dc-05-standard-4
        stdin_open: true 
        tty: true
        volumes:
            - .:/volume/
        deploy:
            replicas: 4
            resources:
                limits:
                  cpus: '16.0'
                  memory: 64G
        cap_add:
            - NET_ADMIN
    
    
