version: '3'
services:
    head:
        image: "ompc-mpi-base:latest"
        hostname: head
        stdin_open: true    # docker run -i
        tty: true           # docker run -t
        volumes:
            - .:/volume/
        cap_add:
            - NET_ADMIN
        networks:
            - 1_global

    proxy:
        image: "ompc-mpi-base:latest"
        hostname: proxy
        stdin_open: true 
        tty: true
        volumes:
            - .:/volume/
        deploy:
            replicas: 1
            resources:
                limits:
                  cpus: '4.0'
                  memory: 16G
        cap_add:
            - NET_ADMIN
        networks:
            - 0_local
            - 1_global


    worker_a:
        image: "ompc-mpi-base:latest"
        hostname: worker_a
        stdin_open: true 
        tty: true
        volumes:
            - .:/volume/
        deploy:
            replicas: 1
            resources:
                limits:
                  cpus: '4.0'
                  memory: 16G
        cap_add:
            - NET_ADMIN
        networks:
            - 0_local
 
    worker_b:
        image: "ompc-mpi-base:latest"
        hostname: worker_b
        stdin_open: true 
        tty: true
        volumes:
            - .:/volume/
        deploy:
            replicas: 1
            resources:
                limits:
                  cpus: '8.0'
                  memory: 32G
        cap_add:
            - NET_ADMIN
        networks:
            - 0_local
 
    proxy_c:
        image: "ompc-mpi-base:latest"
        hostname: proxy_c
        stdin_open: true 
        tty: true
        volumes:
            - .:/volume/
        deploy:
            replicas: 1
            resources:
                limits:
                  cpus: '4.0'
                  memory: 16G
        cap_add:
            - NET_ADMIN
        networks:
            - 0_local_c
            - 1_global
            
    worker_c:
        image: "ompc-mpi-base:latest"
        hostname: worker_c
        stdin_open: true 
        tty: true
        volumes:
            - .:/volume/
        deploy:
            replicas: 1
            resources:
                limits:
                  cpus: '8.0'
                  memory: 32G
        cap_add:
            - NET_ADMIN
        networks:
            - 0_local_c

networks:
    0_local:
    0_local_c:
    1_global:
